import { FaRobot, FaTimes } from 'react-icons/fa';
import { useSelector, useDispatch } from 'react-redux';
import { closeAISummaryModal } from '../../Redux/blogSlice';

const AISummaryModal = () => {
   const {title, summary} = useSelector((state) => state?.blog?.currentPost?.postDetails);
    const isModalOpen = useSelector((state) => state?.blog?.isModalOpen);
    const dispatch = useDispatch();

  if (isModalOpen) return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full mx-4 max-h-[80vh] overflow-hidden">
        <div className="flex items-center justify-between p-4 border-b">
          <div className="flex items-center gap-2">
            <FaRobot className="text-blue-500 text-xl" />
            <h3 className="text-lg font-semibold">AI Summary</h3>
          </div>
          <button
            onClick={() => dispatch(closeAISummaryModal())}
            className="text-gray-500 hover:text-gray-700 transition-colors"
          >
            <FaTimes className="text-xl" />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto max-h-[60vh]">
            <div className="prose prose-sm max-w-none">
              <h4 className="text-lg font-semibold mb-3">{title}</h4>
              <div className="whitespace-pre-line text-gray-700">
                {summary}
              </div>
            </div>
        </div>
        
        <div className="p-4 border-t bg-gray-50">
          <p className="text-xs text-gray-500 text-center">
            This summary was generated by AI. Please verify important information.
          </p>
        </div>
      </div>
    </div>
  ); 
  else return <div></div>
};

export default AISummaryModal;
